export const LABELS = {
  "Number slider": "数字滑条",
  "Finite numerical value": "有限数值",
  number: "数值",
  size: "大小",
  distance: "距离",
  bandwidth: "带宽",
  cellSize: "网格大小",
  Input: "输入",
  "Vector analysis": "矢量分析",
  Output: "输出",
  "Coordinate / Grid": "坐标 / 网格",
  Terrain: "地形",
  Sandbox: "沙盒",
  Style: "样式",
  "Fishnet input": "渔网输入",
  "Point input": "点数据输入",
  "Polygon input": "面数据输入",
  "Raster input": "栅格输入",
  "Vector input": "矢量输入",
  "EPW input": "EPW 气象输入",
  "Area / length": "面积 / 长度",
  "Field statistics": "字段统计",
  "Representative points": "代表点",
  Buffer: "缓冲区",
  "Point kernel density": "点核密度",
  "Result layer": "结果图层",
  "Statistics report": "统计报告",
  "Clip grid by boundary": "按边界裁剪网格",
  "Raster → metric grid": "栅格 → 米制网格",
  "Flatten building ground": "平整建筑下方地面",
  "Continuous surface": "连续地形面",
  "Safe formula": "安全公式",
  "Colour ramp": "色带",
  "Scene preview": "场景预览",
  raster: "栅格",
  vector: "矢量",
  points: "点",
  polygons: "面",
  grid: "网格",
  terrain: "地形",
  weather: "气象",
  summary: "统计",
  scene: "场景",
  result: "结果",
  features: "要素",
  align: "对齐",
  boundary: "边界",
  buildings: "建筑",
  analysis: "分析",
  out: "输出",
  "Geo-referenced numeric or RGB raster": "包含空间参考的数值或 RGB 栅格",
  "GeoJSON feature collection (WGS84)": "GeoJSON 要素集（WGS84）",
  "Point / MultiPoint features (WGS84)": "点 / 多点要素（WGS84）",
  "Polygon / MultiPolygon features (WGS84)": "面 / 多面要素（WGS84）",
  "Aligned metric fishnet: CRS, cell size, values, NoData":
    "已对齐米制渔网：坐标系、格网大小、数值、无数据标记",
  "Continuous mesh from a metric grid": "由米制网格生成的连续曲面",
  "EPW station and hourly weather records": "EPW 气象站与逐时记录",
  "Named statistical values": "带字段名的统计值",
  "Published result": "已输出结果",
};
export const localLabel = (s, t) => t(s, LABELS[s] || s);
export const portLabel = (s, t) =>
  localLabel(s.replace("?", ""), t) + (s.endsWith("?") ? "?" : "");
