import {useI18n} from './i18n.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {X,ChevronLeft,ChevronRight,LocateFixed} from 'lucide-react';
import {usePointerDrag} from './PanelResize.jsx';
import {featureId,selectByAttribute} from './controls.mjs';

export function Transparency({label,value,onChange,disabled=false}) {
 const {t}=useI18n();
 return <label className="transparency-control"><span>{t(label)}<output>{t(value)}%</output></span><input aria-label={t(label)} type="range" min="0" max="100" step="1" value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/></label>;
}

export default function AttributeTable({dataset,metadata,layer,onLayer,selection,onSelection,onClose,settings,onOpacity,onLocate,onError,height,onHeight}) {
 const {t}=useI18n(),drag=usePointerDrag();
 const [field,setField]=useState(''),[operator,setOperator]=useState('gt'),[value,setValue]=useState(''),[page,setPage]=useState(0),[onlySelected,setOnlySelected]=useState(false);
 const features=dataset[layer]?.features||[],idField=metadata[layer]?.idField||'stable_id';
 const columns=useMemo(()=>[...new Set(features.flatMap(f=>Object.keys(f.properties)))],[features]);
 const active=selection.layer===layer?selection.ids:[],selectedSet=useMemo(()=>new Set(active),[active]);
 const rows=onlySelected?features.filter(f=>selectedSet.has(featureId(f,idField))):features;
 const pages=Math.max(1,Math.ceil(rows.length/50)),current=Math.min(page,pages-1);
 useEffect(()=>{setField(columns.includes('height')?'height':columns[0]||'');setPage(0);setValue('');setOnlySelected(false);},[layer,columns]);
 const choose=()=>{try{const ids=selectByAttribute(features,{field,operator,value},idField);onSelection({layer,ids});setPage(0);onError('');}catch(e){onError(e.message);}};
 const toggle=id=>onSelection({layer,ids:selectedSet.has(id)?active.filter(x=>x!==id):[...active,id]});
 return <section className={'attribute-table '+(height<220?'compact-table':'')} aria-label={t("图层属性表")}><div className="panel-resize" role="separator" aria-label={t('调整属性表高度')} aria-orientation="horizontal" aria-valuenow={Math.round(height)} tabIndex={0} onPointerDown={e=>drag(e,(_,dy)=>onHeight(height-dy))} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();onHeight(height+(e.key==='ArrowUp'?20:-20));}}}><span/></div><header><div><strong>{t("属性表")}</strong><select aria-label={t("属性表图层")} value={layer} onChange={e=>onLayer(e.target.value)}>{Object.keys(dataset).map(k=><option key={k} value={k}>{t(metadata[k]?.name||k)}</option>)}</select><span data-testid="selection-count">{t("已选 ")}{active.length.toLocaleString()} / {features.length.toLocaleString()}</span></div><button aria-label={t("关闭属性表")} onClick={onClose}><X size={18}/></button></header>
 <div className="attribute-query"><select aria-label={t("选择属性字段")} value={field} onChange={e=>setField(e.target.value)}>{columns.map(c=><option key={c} value={c}>{c}</option>)}</select><select aria-label={t("属性比较方式")} value={operator} onChange={e=>setOperator(e.target.value)}>{Object.entries({eq:'等于',ne:'不等于',gt:'大于',gte:'大于等于',lt:'小于',lte:'小于等于',contains:'包含',empty:'为空',notempty:'非空'}).map(([v,label])=><option value={v} key={v}>{t(label)}</option>)}</select><input aria-label={t("属性比较值")} placeholder={t("输入属性值")} disabled={['empty','notempty'].includes(operator)} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&choose()}/><button className="query-button" onClick={choose}>{t("按属性选择")}</button><button onClick={()=>onSelection({layer,ids:[]})}>{t("清除选择")}</button><button title={t("定位已选要素")} aria-label={t("定位已选要素")} disabled={!active.length} onClick={()=>onLocate(features.filter(f=>selectedSet.has(featureId(f,idField))))}><LocateFixed size={16}/></button><label className="only-selected"><input type="checkbox" checked={onlySelected} onChange={e=>{setOnlySelected(e.target.checked);setPage(0);}}/>{t("仅查看已选")}</label></div>
 <div className="attribute-style"><Transparency label={t("图层透明度")} value={settings[layer]?.transparency??30} onChange={v=>onOpacity(layer,v,'layer')}/><Transparency label={t("已选要素透明度")} value={settings[layer]?.selectedTransparency??15} onChange={v=>onOpacity(layer,v,'selected')} disabled={!active.length}/><span>{t("0% 不透明 · 100% 完全透明")}</span></div>
 <div className="table-scroll"><table><thead><tr><th><input aria-label={t("选择当前页")} type="checkbox" checked={rows.length>0&&rows.slice(current*50,(current+1)*50).every(f=>selectedSet.has(featureId(f,idField)))} onChange={e=>{const ids=rows.slice(current*50,(current+1)*50).map(f=>featureId(f,idField));onSelection({layer,ids:e.target.checked?[...new Set([...active,...ids])]:active.filter(x=>!ids.includes(x))});}}/></th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(current*50,(current+1)*50).map(f=>{const id=featureId(f,idField);return <tr key={id} className={selectedSet.has(id)?'row-selected':''} onClick={()=>toggle(id)}><td><input aria-label={t('选择记录 '+id)} type="checkbox" checked={selectedSet.has(id)} onChange={()=>toggle(id)} onClick={e=>e.stopPropagation()}/></td>{columns.map(c=><td key={c} title={t(f.properties[c]==null?'空值':String(f.properties[c]))}>{f.properties[c]==null?<span className="null-value">NULL</span>:String(f.properties[c])}</td>)}</tr>;})}</tbody></table>{!rows.length&&<div className="table-empty">{t("没有符合当前查看条件的记录")}</div>}</div>
 <footer><span>{t("每页 50 条 · 地图保留所有要素")}</span><div><button aria-label={t("上一页")} disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={15}/></button><span>{t(current+1)} / {t(pages)}</span><button aria-label={t("下一页")} disabled={current>=pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={15}/></button></div></footer></section>;
}
