import React,{useEffect,useMemo,useState} from 'react';
import {X,ChevronLeft,ChevronRight,LocateFixed} from 'lucide-react';
import {featureId,selectByAttribute} from './controls.mjs';

export function Transparency({label,value,onChange,disabled=false}) {
 return <label className="transparency-control"><span>{label}<output>{value}%</output></span><input aria-label={label} type="range" min="0" max="100" step="1" value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/></label>;
}

export default function AttributeTable({dataset,metadata,layer,onLayer,selection,onSelection,onClose,settings,onOpacity,onLocate,onError}) {
 const [field,setField]=useState(''),[operator,setOperator]=useState('gt'),[value,setValue]=useState(''),[page,setPage]=useState(0),[onlySelected,setOnlySelected]=useState(false);
 const features=dataset[layer]?.features||[],idField=metadata[layer]?.idField||'stable_id';
 const columns=useMemo(()=>[...new Set(features.flatMap(f=>Object.keys(f.properties)))],[features]);
 const active=selection.layer===layer?selection.ids:[],selectedSet=useMemo(()=>new Set(active),[active]);
 const rows=onlySelected?features.filter(f=>selectedSet.has(featureId(f,idField))):features;
 const pages=Math.max(1,Math.ceil(rows.length/50)),current=Math.min(page,pages-1);
 useEffect(()=>{setField(columns.includes('height')?'height':columns[0]||'');setPage(0);setValue('');setOnlySelected(false);},[layer,columns]);
 const choose=()=>{try{const ids=selectByAttribute(features,{field,operator,value},idField);onSelection({layer,ids});setPage(0);onError('');}catch(e){onError(e.message);}};
 const toggle=id=>onSelection({layer,ids:selectedSet.has(id)?active.filter(x=>x!==id):[...active,id]});
 return <section className="attribute-table" aria-label="图层属性表"><header><div><strong>属性表</strong><select aria-label="属性表图层" value={layer} onChange={e=>onLayer(e.target.value)}>{Object.keys(dataset).map(k=><option key={k} value={k}>{metadata[k]?.name||k}</option>)}</select><span data-testid="selection-count">已选 {active.length.toLocaleString()} / {features.length.toLocaleString()}</span></div><button aria-label="关闭属性表" onClick={onClose}><X size={18}/></button></header>
 <div className="attribute-query"><select aria-label="选择属性字段" value={field} onChange={e=>setField(e.target.value)}>{columns.map(c=><option key={c}>{c}</option>)}</select><select aria-label="属性比较方式" value={operator} onChange={e=>setOperator(e.target.value)}>{Object.entries({eq:'等于',ne:'不等于',gt:'大于',gte:'大于等于',lt:'小于',lte:'小于等于',contains:'包含',empty:'为空',notempty:'非空'}).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select><input aria-label="属性比较值" placeholder="输入属性值" disabled={['empty','notempty'].includes(operator)} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&choose()}/><button className="query-button" onClick={choose}>按属性选择</button><button onClick={()=>onSelection({layer,ids:[]})}>清除选择</button><button title="定位已选要素" aria-label="定位已选要素" disabled={!active.length} onClick={()=>onLocate(features.filter(f=>selectedSet.has(featureId(f,idField))))}><LocateFixed size={16}/></button><label className="only-selected"><input type="checkbox" checked={onlySelected} onChange={e=>{setOnlySelected(e.target.checked);setPage(0);}}/>仅查看已选</label></div>
 <div className="attribute-style"><Transparency label="图层透明度" value={settings[layer]?.transparency??30} onChange={v=>onOpacity(layer,v,'layer')}/><Transparency label="已选要素透明度" value={settings[layer]?.selectedTransparency??15} onChange={v=>onOpacity(layer,v,'selected')} disabled={!active.length}/><span>0% 不透明 · 100% 完全透明</span></div>
 <div className="table-scroll"><table><thead><tr><th><input aria-label="选择当前页" type="checkbox" checked={rows.length>0&&rows.slice(current*50,(current+1)*50).every(f=>selectedSet.has(featureId(f,idField)))} onChange={e=>{const ids=rows.slice(current*50,(current+1)*50).map(f=>featureId(f,idField));onSelection({layer,ids:e.target.checked?[...new Set([...active,...ids])]:active.filter(x=>!ids.includes(x))});}}/></th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(current*50,(current+1)*50).map(f=>{const id=featureId(f,idField);return <tr key={id} className={selectedSet.has(id)?'row-selected':''} onClick={()=>toggle(id)}><td><input aria-label={'选择记录 '+id} type="checkbox" checked={selectedSet.has(id)} onChange={()=>toggle(id)} onClick={e=>e.stopPropagation()}/></td>{columns.map(c=><td key={c} title={f.properties[c]==null?'空值':String(f.properties[c])}>{f.properties[c]==null?<span className="null-value">NULL</span>:String(f.properties[c])}</td>)}</tr>;})}</tbody></table>{!rows.length&&<div className="table-empty">没有符合当前查看条件的记录</div>}</div>
 <footer><span>每页 50 条 · 地图保留所有要素</span><div><button aria-label="上一页" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={15}/></button><span>{current+1} / {pages}</span><button aria-label="下一页" disabled={current>=pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={15}/></button></div></footer></section>;
}
