import React,{useState} from 'react';
import {Send,PlugZap,Workflow} from 'lucide-react';
import {useI18n} from './i18n.jsx';
import {chatPresets,parseChat} from './chat-commands.mjs';
export default function ChatPanel({messages,setMessages,onCommand,onBuilder}){
 const {t}=useI18n(),[text,setText]=useState(''),[mode,setMode]=useState('local'),[settings,setSettings]=useState(false),[provider,setProvider]=useState('OpenAI'),[busy,setBusy]=useState(false);
 const send=async value=>{if(!value.trim()||busy)return;setBusy(true);setText('');setMessages(m=>[...m,{role:'user',text:value}]);try{if(mode!=='local')throw new Error('模型连接尚未配置，请先使用本地预设。');const response=await onCommand(parseChat(value));setMessages(m=>[...m,{role:'assistant',text:response}]);}catch(e){setMessages(m=>[...m,{role:'assistant',text:e.message,error:true}]);}finally{setBusy(false);}};
 return <div className="geocimai-chat"><div className="chat-heading"><b>{t("与GeoCIM对话")}</b><button aria-label={t('连接账号 / API')} onClick={()=>setSettings(!settings)}><PlugZap size={16}/></button></div>
 <label className="field-label">{t('对话模式')}<select aria-label={t('对话模式')} value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value==='api')setSettings(true);}}><option value="local">{t('本地预设')}</option><option value="api">{t('模型 API · 待连接')}</option></select></label>
 {settings&&<div className="connection-card"><h3>{t('连接账号 / API')}</h3><select aria-label={t('模型服务')} value={provider} onChange={e=>setProvider(e.target.value)}><option>OpenAI</option><option>DeepSeek</option></select><p><b>{provider}</b> · {t('尚未连接')}</p><p>{t('当前预留连接入口。OpenAI API 通过服务端密钥连接；ChatGPT 网页登录不会自动授权本站。')}</p>{provider==='OpenAI'&&<a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">{t('打开 OpenAI API 控制台')}</a>}<p>{t('后续启用账号权限、额度与限流后，模型才能控制地图和生成电池流程。')}</p></div>}
 <div className="chat-messages" role="log" aria-label={t('对话记录')}>{!messages.length?<div className="chat-welcome"><Workflow size={28}/><h3>{t('从一个空间问题开始')}</h3><p>{t('预设可以操作地图，也可以生成 Circuit 电路。')}</p></div>:messages.map((m,i)=><div className={'chat-bubble '+m.role+(m.error?' failed':'')} key={i}>{m.role==='assistant'&&<small>GeoCIM · {t('本地预设')}</small>}<p>{m.role==='assistant'?t(m.text):m.text}</p></div>)}</div>
 <div className="chat-presets">{chatPresets.map(s=><button key={s} disabled={busy||mode!=='local'} onClick={()=>send(t(s))}>{t(s)}</button>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();send(text);}}><textarea aria-label={t('输入地图指令')} placeholder={t('输入指令，或选择一个预设…')} value={text} maxLength={1000} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(text);}}}/><button aria-label={t('发送指令')} disabled={busy||!text.trim()}><Send size={17}/></button></form><button className="secondary" onClick={onBuilder}>{t('打开模型建构器')}</button><p className="help">{t('当前仅运行本地预设；不发送数据，不产生模型费用。')}</p></div>;
}
