import React,{useState,useRef,useEffect,useMemo} from 'react';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position} from '@xyflow/react';
import {X,Play,Plus,Download,Upload,Trash2,Workflow} from 'lucide-react';
import {batteries,defaults,cleanGraph,demoGraph} from './circuit.mjs';
import {runJob} from './jobs.mjs';
import {downloadJSON} from './download.mjs';
import {useI18n} from './i18n.jsx';
import '@xyflow/react/dist/style.css';
import './circuit.css';
import {clamp,usePointerDrag} from './PanelResize.jsx';

function Battery({data}){
 return <div className={'battery '+(data.active?'active':'')}>
 {data.input&&<Handle type="target" position={Position.Left} aria-label={data.title+' input'}/>}
 <div className="battery-head"><span>{data.code}</span><b>{data.title}</b><i className={data.done?'done':''}/></div>
 <p>{data.detail}</p><footer>{data.done?data.count+' · '+data.completed:data.code==='SOURCE'?'GeoJSON':data.summary?'Table':'Vector'}</footer>
 {data.output&&<Handle type="source" position={Position.Right} aria-label={data.title+' output'}/>}
 </div>;
}
const nodeTypes={battery:Battery};
export default function CircuitBuilder({graph,setGraph,dataset,metadata,onResults,onClose,layerCount,onDockHeight}){
 const {t,lang}=useI18n(),[selected,setSelected]=useState(graph.nodes[0]?.id),[wire,setWire]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[log,setLog]=useState([]),[summaries,setSummaries]=useState([]),[recipe,setRecipe]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[template,setTemplate]=useState('density');
 const job=useRef(null),input=useRef(null),flow=useRef(null);
 const panel=useRef(null),drag=usePointerDrag(),[docked,setDocked]=useState(true),[height,setHeight]=useState(()=>Math.round(window.innerHeight*.43)),[rect,setRect]=useState({x:30,y:100,width:900,height:440});
 const limitHeight=value=>clamp(value,240,Math.max(240,window.innerHeight-220));
 useEffect(()=>{onDockHeight(docked?height:0);return()=>onDockHeight(0);},[docked,height,onDockHeight]);
 useEffect(()=>{const resize=()=>{setHeight(h=>limitHeight(h));setRect(r=>({...r,width:Math.min(r.width,window.innerWidth-16),height:Math.min(r.height,window.innerHeight-80),x:clamp(r.x,8,window.innerWidth-Math.min(r.width,window.innerWidth-16)-8),y:clamp(r.y,66,window.innerHeight-100)}));};window.addEventListener('resize',resize);return()=>{window.removeEventListener('resize',resize);job.current?.cancel();};},[]);
 const floatWindow=()=>{const width=Math.min(window.innerWidth-32,1200);setRect({x:(window.innerWidth-width)/2,y:Math.max(75,window.innerHeight-height-35),width,height});setDocked(false);};
 const moveWindow=e=>{if(e.target.closest('button'))return;const old=panel.current.getBoundingClientRect(),width=docked?Math.min(window.innerWidth-32,1200):old.width;const start={x:docked?clamp(e.clientX-width/2,8,window.innerWidth-width-8):old.left,y:old.top,width,height:old.height};setRect(start);setDocked(false);drag(e,(dx,dy)=>setRect({...start,x:clamp(start.x+dx,8,window.innerWidth-width-8),y:clamp(start.y+dy,66,Math.max(66,window.innerHeight-start.height-8))}),ev=>{if(ev.type!=='pointercancel'&&ev.clientY>window.innerHeight-100)setDocked(true);});};
 const resizeHeight=e=>{const old=panel.current.getBoundingClientRect();drag(e,(_,dy)=>{if(docked)setHeight(limitHeight(old.height-dy));else{const h=clamp(old.height-dy,240,old.bottom-66);setRect(r=>({...r,y:old.bottom-h,height:h}));}});};
 const resizeCorner=e=>{const old=panel.current.getBoundingClientRect();drag(e,(dx,dy)=>setRect(r=>({...r,width:clamp(old.width+dx,Math.min(650,window.innerWidth-16),window.innerWidth-r.x-8),height:clamp(old.height+dy,240,window.innerHeight-r.y-8)})));};
 const current=graph.nodes.find(n=>n.id===selected);
 useEffect(()=>{setRecipe(JSON.stringify(current?.params.steps||defaults.recipe.steps,null,2));},[selected,current?.params.steps]);
 const change=next=>{setGraph(next);setLog([]);setSummaries([]);};
 const patch=params=>change({...graph,nodes:graph.nodes.map(n=>n.id===selected?{...n,params:{...n.params,...params}}:n)});
 const add=type=>{if(graph.nodes.length>=40)return setError(t('最多 40 个电池。'));const id='cell-'+crypto.randomUUID();change({...graph,nodes:[...graph.nodes,{id,type,position:{x:100+graph.nodes.length%4*255,y:100+Math.floor(graph.nodes.length/4)*190},params:{...structuredClone(defaults[type]),...(type==='source'?{layer:Object.keys(dataset)[0]||'buildings'}:{})}}]});setSelected(id);setError('');};
 const connect=({source,target})=>{try{change(cleanGraph({...graph,edges:[...graph.edges,{source,target}]}));setError('');}catch(e){setError(e.message);}};
 const remove=()=>{if(wire){change({...graph,edges:graph.edges.filter(e=>e.id!==wire)});setWire('');}else if(selected){change({...graph,nodes:graph.nodes.filter(n=>n.id!==selected),edges:graph.edges.filter(e=>e.source!==selected&&e.target!==selected)});setSelected('');}};
 const load=async file=>{try{if(!file||file.size>1024*1024)throw new Error('流程文件最大 1 MiB。');const restored=cleanGraph(JSON.parse(await file.text()));change(restored);setSelected(restored.nodes[0].id);setError('');setTimeout(()=>flow.current?.fitView({padding:.2}),100);}catch(e){setError(e.message);}if(input.current)input.current.value='';};
 const run=async()=>{setError('');setBusy(true);setLog([]);setSummaries([]);setProgress(0);try{
  const normalized=cleanGraph(graph);if(normalized.nodes.filter(n=>n.type==='output').length+layerCount>20)throw new Error('当前工作空间最多 20 个图层，请先移除部分图层。');
  job.current=runJob({job:'circuit',graph:normalized,dataset,metadata:Object.fromEntries(Object.entries(metadata).map(([k,m])=>[k,{name:t(m.name)}])),runId:'circuit-'+crypto.randomUUID()},(value,event)=>{setProgress(value);if(event.log)setLog(event.log);});
  const result=await job.current.promise;job.current=null;setLog(result.log);setSummaries(result.outputs.filter(r=>r.kind==='summary'));onResults(result.outputs.filter(r=>r.kind==='vector'));
 }catch(e){setError(e.message);}finally{job.current=null;setBusy(false);}};
 const nodes=useMemo(()=>graph.nodes.map(n=>({id:n.id,type:'battery',position:n.position,selected:n.id===selected,data:{title:t(batteries[n.type].label),code:n.type.toUpperCase(),input:batteries[n.type].input,output:!!batteries[n.type].output,summary:n.type==='statistics',active:n.id===selected,done:log.some(l=>l.id===n.id),count:log.find(l=>l.id===n.id)?.count??'',completed:t('完成'),detail:n.type==='source'?t(metadata[n.params.layer]?.name||'请绑定图层'):n.type==='buffer'?`${n.params.distance} m`:n.type==='kde'?`h ${n.params.bandwidth} m · grid ${n.params.cellSize} m`:n.type==='select'?`${n.params.field} ${n.params.operator} ${n.params.value??''}`:n.type==='statistics'?n.params.field:n.type==='recipe'?`${n.params.steps.length} ${t('步骤')}`:t(n.type==='output'?'加入地图 / 下载表格':'本地计算')}})),[graph,selected,log,lang,metadata]);
 const fields=Object.values(dataset).length?[...new Set(Object.values(dataset).flatMap(d=>d.features.slice(0,100).flatMap(f=>Object.keys(f.properties))))]:[];
 const textField=(key,label)=> <label className="field-label">{t(label)}<input aria-label={t(label)} list="circuit-fields" value={current.params[key]??''} onChange={e=>patch({[key]:e.target.value})}/></label>;
 const numberField=(key,label)=> <label className="field-label">{t(label)}<input aria-label={t(label)} type="number" value={current.params[key]??''} onChange={e=>patch({[key]:e.target.value})}/></label>;
 return <div ref={panel} className={'circuit-overlay circuit-window '+(docked?'docked':'floating')} style={docked?{height}:{left:rect.x,top:rect.y,width:rect.width,height:rect.height}} role="region" aria-label={t('模型建构器')}>
 <div className="panel-resize" role="separator" aria-orientation="horizontal" aria-label={t('调整模型建构器高度')} tabIndex={0} aria-valuenow={Math.round(docked?height:rect.height)} onPointerDown={resizeHeight} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const d=e.key==='ArrowUp'?20:-20;if(docked)setHeight(h=>limitHeight(h+d));else setRect(r=>({...r,height:clamp(r.height+d,240,window.innerHeight-r.y-8)}));}}}><span/></div>
 <div className="circuit-header" onPointerDown={moveWindow} title={t('拖动标题栏移动窗口，拖到底部停靠')}><div><Workflow size={23}/><b>GeoCIM Circuit</b><span>{t('空间电路 · 模型建构器')}</span></div><div className="window-actions"><button onClick={()=>docked?floatWindow():setDocked(true)}>{t(docked?'浮动窗口':'停靠下方')}</button><button aria-label={t('关闭模型建构器')} onClick={onClose}><X size={20}/></button></div></div>
 <div className="circuit-toolbar"><select aria-label={t('流程预设')} disabled={busy} value={template} onChange={e=>setTemplate(e.target.value)}><option value="density">{t('代表点 → 核密度')}</option><option value="buffer">{t('高度选择 → 缓冲区')}</option><option value="statistics">{t('字段统计流程')}</option></select><button disabled={busy} onClick={()=>{const g=demoGraph(Object.keys(dataset)[0]||'buildings',template);change(g);setSelected(g.nodes[0].id);setError('');setTimeout(()=>flow.current?.fitView({padding:.2}),100);}}>{t('载入预设')}</button><button disabled={busy} onClick={()=>{try{downloadJSON(cleanGraph(graph),'GeoCIM-Circuit.json');}catch(e){setError(e.message);}}}><Download size={14}/>{t('保存流程')}</button><button disabled={busy} onClick={()=>input.current.click()}><Upload size={14}/>{t('打开流程')}</button><input ref={input} type="file" accept=".json" aria-label={t('选择流程文件')} hidden onChange={e=>load(e.target.files[0])}/><div className="circuit-spacer"/><button className="circuit-run" disabled={busy||!Object.keys(dataset).length} onClick={run}><Play size={14}/>{busy?`${t('运行中')} ${progress}%`:t('运行流程')}</button>{busy&&<button onClick={()=>job.current?.cancel()}>{t('取消任务')}</button>}</div>
 {error&&<div className="circuit-error" role="alert">{t(error)}</div>}
 <div className="circuit-body"><div className="battery-library"><h3>{t('本地电池')}</h3>{Object.entries(batteries).map(([type,b])=><button key={type} disabled={busy} onClick={()=>add(type)} aria-label={t('添加电池')+' '+t(b.label)}><Plus size={13}/>{t(b.label)}</button>)}<h3>Food4CIM</h3><p>{t('扩展接口 · 规划中')}</p>{['两步移动搜索法','选址决策','批量裁剪'].map(s=><div className="future-battery" key={s}>{t(s)}<small>{t('预留')}</small></div>)}<p className="circuit-note">{t('拖动电池，连接左右端口。选中连线或电池后可删除。')}</p></div>
 <div className="circuit-canvas"><ReactFlow nodes={nodes} edges={graph.edges.map(e=>({...e,type:'smoothstep',animated:busy,selected:e.id===wire,style:{stroke:e.id===wire?'#b78f3b':'#927bb8',strokeWidth:2}}))} nodeTypes={nodeTypes} onInit={instance=>{flow.current=instance;}} onConnect={connect} onNodeClick={(_,n)=>{setSelected(n.id);setWire('');}} onEdgeClick={(_,e)=>{setWire(e.id);setSelected('');}} onNodesChange={changes=>{if(busy)return;const positions=changes.filter(c=>c.type==='position'&&c.position);if(positions.length)setGraph(g=>({...g,nodes:g.nodes.map(n=>({...n,position:positions.find(c=>c.id===n.id)?.position||n.position}))}));}} nodesDraggable={!busy} nodesConnectable={!busy} elementsSelectable={!busy} connectOnClick fitView fitViewOptions={{padding:.2}} minZoom={.2} maxZoom={1.8} deleteKeyCode={null}><Background gap={22} size={1} color="#d8d3e2"/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="#ab97d0"/></ReactFlow><div className="circuit-hint">{t('滚轮缩放 · 拖动空白平移')} · {graph.nodes.length} {t('电池')}</div></div>
 <div className="battery-inspector"><h3>{t('电池参数')}</h3><fieldset disabled={busy}>
 {current?<><b>{t(batteries[current.type].label)}</b><small className="cell-id">{current.id}</small>
 {current.type==='source'&&<label className="field-label">{t('输入图层')}<select aria-label={t('电池输入图层')} value={current.params.layer} onChange={e=>patch({layer:e.target.value})}><option value="">{t('请绑定图层')}</option>{!dataset[current.params.layer]&&current.params.layer&&<option value={current.params.layer}>{current.params.layer} ({t('需要重新绑定')})</option>}{Object.keys(dataset).map(k=><option key={k} value={k}>{t(metadata[k]?.name||k)}</option>)}</select></label>}
 {['select','statistics'].includes(current.type)&&textField('field','字段')}
 {current.type==='select'&&<><label className="field-label">{t('比较方式')}<select aria-label={t('电池比较方式')} value={current.params.operator} onChange={e=>patch({operator:e.target.value})}>{['gt','gte','lt','lte','eq','ne','contains','empty','notempty'].map(k=><option key={k}>{k}</option>)}</select></label>{textField('value','比较值')}</>}
 {current.type==='buffer'&&numberField('distance','缓冲距离（米）')}
 {current.type==='kde'&&<>{numberField('bandwidth','带宽（米）')}{numberField('cellSize','网格边长（米）')}{textField('weightField','权重字段')}<p>{t('留空表示每点权重为 1。')}</p></>}
 {current.type==='recipe'&&<><p>{t('编辑白名单步骤 JSON；未来 AI 可生成同一格式。')}</p><textarea className="recipe-editor" aria-label={t('微流程代码')} value={recipe} onChange={e=>setRecipe(e.target.value)}/><button onClick={()=>{try{const steps=JSON.parse(recipe);const g={...graph,nodes:graph.nodes.map(n=>n.id===selected?{...n,params:{steps}}:n)};change(cleanGraph(g));setError('');}catch(e){setError(e.message);}}}>{t('应用代码')}</button></>}
 {['centroid','measure','output'].includes(current.type)&&<p>{t({centroid:'代表点为顶点平均位置，不等于人口分配。',measure:'输出面积 m² 和线长 m。',output:'运行成功后加入地图；统计结果在下方下载。'}[current.type])}</p>}
 </>:<p>{t('选择电池以编辑参数。')}</p>}
 <datalist id="circuit-fields">{fields.map(f=><option key={f} value={f}/>)}</datalist>
 <button className="delete-cell" disabled={!selected&&!wire} onClick={remove}><Trash2 size={13}/>{t(wire?'删除连线':'删除电池')}</button>
 <details><summary>{t('精确连接')}</summary><label>{t('从')}<select aria-label={t('连线起点')} value={from} onChange={e=>setFrom(e.target.value)}><option value="">—</option>{graph.nodes.filter(n=>batteries[n.type].output).map(n=><option key={n.id} value={n.id}>{t(batteries[n.type].label)} · {n.id.slice(-6)}</option>)}</select></label><label>{t('到')}<select aria-label={t('连线终点')} value={to} onChange={e=>setTo(e.target.value)}><option value="">—</option>{graph.nodes.filter(n=>batteries[n.type].input).map(n=><option key={n.id} value={n.id}>{t(batteries[n.type].label)} · {n.id.slice(-6)}</option>)}</select></label><button onClick={()=>connect({source:from,target:to})}>{t('连接电池')}</button></details></fieldset>
 <h3>{t('运行记录')}</h3><div className="circuit-log" role="status">{log.length?log.map(l=><p key={l.id}>✓ {t(batteries[l.type].label)} · {l.count}</p>):<p>{t('尚未运行')}</p>}</div>{summaries.map((s,i)=><div className="circuit-summary" key={i}><b>{t('统计结果')}</b><p>{t('有效数值')}: {s.values.valid} · {t('平均值')}: {s.values.mean?.toFixed(3)??'—'}</p><button onClick={()=>downloadJSON(s,'Circuit-statistics.json')}>{t('下载统计结果')}</button></div>)}
 </div></div><footer className="circuit-footer">{t('流程文件只保存电池与参数，不包含原始数据。重新打开时可重新绑定图层。')}</footer>{!docked&&<div className="window-corner" aria-label={t("调整窗口大小")} onPointerDown={resizeCorner}/>}</div>;
}
