import React,{useEffect,useMemo,useState,useRef,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import * as Switch from '@radix-ui/react-switch';
import {Layers3,RotateCcw,Layers,X,Table2,Upload,ChartNoAxesCombined,Workflow} from 'lucide-react';
import {featureId,summarize,updateTransparency,selectByAttribute} from './controls.mjs';
import MapView,{geometryBounds} from './MapView.jsx';
import AttributeTable,{Transparency} from './AttributeTable.jsx';
import UploadPanel from './UploadPanel.jsx';
import AnalysisPanel from './AnalysisPanel.jsx';
import ChatPanel from './ChatPanel.jsx';
import {demoGraph} from './circuit.mjs';
import {runJob} from './jobs.mjs';
const CircuitBuilder=lazy(()=>import('./CircuitBuilder.jsx'));
import './circuit.css';
import {clamp} from './PanelResize.jsx';
import {downloadJSON} from './download.mjs';
import {LanguageProvider,useI18n} from './i18n.jsx';
import './style.css';import './workspace.css';import './bilingual.css';import './analysis.css';import './floating-panels.css';
const baseNames={buildings:'建筑',roads:'路网',population:'人口网格',boundary:'边界'};
const initialSettings={buildings:{visible:true,transparency:35,selectedTransparency:15},roads:{visible:true,transparency:15,selectedTransparency:15},population:{visible:false,transparency:55,selectedTransparency:15},boundary:{visible:true,transparency:80,selectedTransparency:15},satellite:{visible:false,transparency:0}};
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw new Error('数据加载失败：'+r.status);return r.json();}
function Toggle({label,checked,onChange}){return <div className="toggle"><span>{label}</span><Switch.Root className="switch" aria-label={label} checked={checked} onCheckedChange={onChange}><Switch.Thumb className="thumb"/></Switch.Root></div>;}
function App(){
 const {lang,setLang,t}=useI18n(),exporter=useRef(null),blobURLs=useRef(new Set());
 const [catalog,setCatalog]=useState(null),[allData,setAllData]=useState({}),[metadata,setMetadata]=useState({}),[allRasters,setAllRasters]=useState([]),[settings,setSettings]=useState(initialSettings),[ready,setReady]=useState(false),[error,setError]=useState('');
 const mapArea=useRef(null),[dockHeight,setDockHeight]=useState(0),[tableSize,setTableSize]=useState(350),[mapHeight,setMapHeight]=useState(700);
 useEffect(()=>{const observer=new ResizeObserver(entries=>setMapHeight(entries[0].contentRect.height));observer.observe(mapArea.current);return()=>observer.disconnect();},[]);
 const tableHeight=clamp(tableSize,110,Math.max(110,mapHeight-180));
 const [builderOpen,setBuilderOpen]=useState(false),[graph,setGraph]=useState(()=>demoGraph()),[analysisMode,setAnalysisMode]=useState('chat'),[messages,setMessages]=useState([]);
 const [workspace,setWorkspace]=useState('demo'),[tab,setTab]=useState('analysis'),[selection,setSelection]=useState({layer:'buildings',ids:[]}),[picked,setPicked]=useState(null),[tableOpen,setTableOpen]=useState(false),[tableLayer,setTableLayer]=useState('buildings'),[threeD,setThreeD]=useState(true),[color,setColor]=useState('height'),[camera,setCamera]=useState(null),[panelTransparency,setPanelTransparency]=useState(62),[exportBusy,setExportBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{(async()=>{
  const [c,buildings,roads,population,boundary]=await Promise.all(['/api/catalog','/api/layers/buildings','/api/layers/roads','/api/layers/population','/api/layers/boundary'].map(getJSON));
  const metas=Object.fromEntries(Object.entries(baseNames).map(([id,name])=>[id,{id,name,idField:'stable_id',kind:'vector',workspace:'demo',heightField:id==='buildings'?'height':''}]));
  setAllData({buildings,roads,population,boundary});setMetadata(metas);setAllRasters(c.satellite?[{id:'satellite',name:'卫星底图',workspace:'demo',display:'灰度',url:'/api/satellite.png',coordinates:c.satellite.coordinates}]:[]);setCatalog(c);setThreeD(c.height_enabled);
 })().catch(e=>setError(e.message));return()=>{blobURLs.current.forEach(url=>URL.revokeObjectURL(url));};},[]);
 const dataset=useMemo(()=>Object.fromEntries(Object.entries(allData).filter(([key])=>metadata[key]?.workspace===workspace)),[allData,metadata,workspace]);
 const rasters=useMemo(()=>allRasters.filter(r=>r.workspace===workspace),[allRasters,workspace]);
 const hasPersonal=Object.values(metadata).some(m=>m.workspace==='personal');
 const stats=useMemo(()=>summarize(dataset.buildings?.features||[]),[dataset]);
 const featureCount=Object.values(dataset).reduce((n,d)=>n+d.features.length,0),layerCount=Object.keys(dataset).length+rasters.length;
 const title=t(workspace==='demo'?'项目：沙头分析':'项目：我的数据');
 useEffect(()=>{if(!dataset[tableLayer]){setTableLayer(Object.keys(dataset)[0]||'');setTableOpen(false);}},[dataset,tableLayer]);
 const toggle=(key,value)=>setSettings(s=>({...s,[key]:{...s[key],visible:value}}));
 const opacity=(layer,value,scope='layer')=>setSettings(s=>updateTransparency(s,{layer,value,scope},Object.keys(s)));
 const select=next=>{setSelection(next);setPicked(null);};
 const openTable=(layer=tableLayer)=>{setTableLayer(layer);setTableOpen(true);setTab('attributes');};
 const locate=features=>{const bounds=geometryBounds(features);if(bounds)setCamera({bounds,token:Date.now()});};
 const reset=()=>{select({layer:tableLayer,ids:[]});const bounds=workspace==='demo'?catalog?.bounds:geometryBounds(Object.values(dataset).flatMap(d=>d.features))||rasters[0]?.bounds;setCamera({bounds,token:Date.now()});setError('');};
 const switchWorkspace=value=>{setWorkspace(value);setPicked(null);setSelection({layer:'',ids:[]});setTableOpen(false);setTab('analysis');setError('');setNotice('');const features=Object.entries(allData).filter(([k])=>metadata[k]?.workspace===value).flatMap(([,d])=>d.features);setCamera({bounds:value==='demo'?catalog?.bounds:geometryBounds(features)||allRasters.find(r=>r.workspace===value)?.bounds||catalog?.bounds,token:Date.now()});};
 useEffect(()=>{if(catalog&&workspace==='personal'&&!hasPersonal)switchWorkspace('demo');},[hasPersonal,workspace,catalog]);
 const addItems=(items,target)=>{
  const prepared=items.map(item=>{if(item.blob){const url=URL.createObjectURL(item.blob);blobURLs.current.add(url);return {...item,url,workspace:target};}return {...item,workspace:target};});
  setAllData(s=>({...s,...Object.fromEntries(prepared.filter(i=>i.kind==='vector').map(i=>[i.id,i.data]))}));
  setMetadata(s=>({...s,...Object.fromEntries(prepared.map(i=>[i.id,i]))}));setAllRasters(s=>[...s,...prepared.filter(i=>i.kind==='raster')]);
  setSettings(s=>({...s,...Object.fromEntries(prepared.map(i=>[i.id,{visible:true,transparency:i.kind==='raster'?0:25,selectedTransparency:15}]))}));
  if(prepared.find(i=>i.kind==='vector'))setTableLayer(prepared.find(i=>i.kind==='vector').id);setCamera({bounds:prepared[0].bounds,token:Date.now()});setPicked(null);
 };
 const imported=items=>{addItems(items,'personal');setWorkspace('personal');setTableOpen(false);setSelection({layer:'',ids:[]});setTab('layers');setNotice('导入完成，已加入我的数据。');};
 const analysisResult=item=>{addItems([item],workspace);setTab('layers');setNotice('分析完成，新结果图层已加入地图。');};
 const removeLayer=key=>{if(metadata[key]?.workspace==='demo'&&!metadata[key]?.analysis)return;const url=metadata[key]?.url;setAllData(s=>{const next={...s};delete next[key];return next;});setAllRasters(s=>s.filter(r=>r.id!==key));setMetadata(s=>{const next={...s};delete next[key];return next;});setSettings(s=>{const next={...s};delete next[key];return next;});setPicked(null);setSelection({layer:'',ids:[]});if(url?.startsWith('blob:')){URL.revokeObjectURL(url);blobURLs.current.delete(url);}};
 const heightField=(key,field)=>{if(field&&allData[key].features.some(f=>f.properties[field]!=null&&(typeof f.properties[field]!=='number'||!Number.isFinite(f.properties[field])||f.properties[field]<0)))return setError(t('高度字段需为非负数值，单位为米；空值按 0 显示。'));setMetadata(s=>({...s,[key]:{...s[key],heightField:field}}));setError('');};
 const exportPNG=async()=>{setExportBusy(true);try{await exporter.current?.({title,note:t(workspace==='demo'?(catalog?.synthetic?'基础图层：模拟数据':'真实数据 · 预设项目'):'个人数据 · 浏览器分析'),stats:workspace==='demo'?`${t('建筑数量')}: ${stats.count} | ${t('平均高度')}: ${stats.mean?.toFixed(1)} m`:`${t('图层数')}: ${layerCount} | ${t('要素数')}: ${featureCount}`,lang,color:workspace==='demo'?color:'uniform'});}catch(e){setError(e.message);}finally{setExportBusy(false);}};
 const handleChat=async command=>{
  const key=dataset.buildings?'buildings':tableLayer,layer=dataset[key];
  if(command.action==='table'){if(!dataset[tableLayer])throw new Error('请先导入数据。');openTable(tableLayer);setTab('analysis');return '已打开属性表。';}
  if(command.action==='select'){if(!layer)throw new Error('请先导入数据。');const ids=selectByAttribute(layer.features,command,metadata[key]?.idField||'stable_id');select({layer:key,ids});openTable(key);setTab('analysis');return `已选 ${ids.length.toLocaleString()} 个要素`;}
  if(command.action==='opacity'){if(!layer)throw new Error('请先导入数据。');opacity(key,command.value);return t(metadata[key].name)+' · '+t('透明度')+' '+command.value+'%';}
  if(command.action==='population'){if(!dataset.population)throw new Error('当前工作空间没有人口网格。');toggle('population',true);return '已显示人口网格。';}
  if(command.action==='clear'){select({layer:tableLayer,ids:[]});return '已清除选择。';}
  if(command.action==='view'){setThreeD(command.threeD);return command.threeD?'3D 视角':'2D 平面';}
  if(command.action==='circuit'){if(!layer)throw new Error('请先导入数据。');setGraph(demoGraph(key,command.template));setBuilderOpen(true);return '电路已生成。检查参数后点击运行流程。';}
  if(command.action==='statistics'){if(!layer)throw new Error('请先导入数据。');const job=runJob({job:'analysis',data:layer,options:{operation:'statistics',field:command.field}});const r=await job.promise;return t('有效数值')+': '+r.values.valid+' · '+t('平均值')+': '+(r.values.mean?.toFixed(3)??'—');}
  throw new Error('未知指令');
 };
 const tabs=[['analysis',ChartNoAxesCombined,'分析'],['layers',Layers,'图层'],['attributes',Table2,'属性表'],['upload',Upload,'上传']];
 return <div className="app" style={{'--panel-alpha':1-panelTransparency/100,'--table-height':tableHeight+'px'}}><header className="topbar"><div className="brand"><div className="brand-icon"><Layers3 size={24}/></div><b>GeoCIM+</b></div><button className="circuit-top" onClick={()=>setBuilderOpen(true)}><Workflow size={17}/>{t('模型建构器')}<span> Circuit</span></button><div className="project-menu"><select aria-label={t('项目空间')} value={workspace} onChange={e=>switchWorkspace(e.target.value)}><option value="demo">{t('沙头分析 · 预设')}</option>{hasPersonal&&<option value="personal">{t('我的数据')}</option>}</select></div><div className="top-meta"><div className="language-switch" aria-label={t('切换语言')}><button aria-pressed={lang==='zh'} onClick={()=>setLang('zh')}>中文</button><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>English</button></div><button className="upload-top" onClick={()=>setTab('upload')}><Upload size={15}/>{t('导入本地数据')}</button></div></header>
 <main style={{marginBottom:builderOpen?dockHeight:0}}><section ref={mapArea} className={'map-area '+(tableOpen?'with-table ':'')+(mapHeight-(tableOpen?tableHeight:0)<380?'short-map':'')}>
 {catalog&&<MapView catalog={catalog} dataset={dataset} metadata={metadata} rasters={rasters} settings={settings} selection={selection} threeD={threeD} color={color} camera={camera} tableOpen={tableOpen} onExporter={fn=>{exporter.current=fn;}} onPick={setPicked} onReady={v=>{setReady(v);setCamera({token:Date.now()});}} onError={setError}/>}
 <div className="map-title"><h1>{title}</h1><p className="demo-badge">{t(workspace==='demo'?(catalog?.synthetic?'基础图层：模拟数据':'真实数据 · 预设项目'):'个人数据 · 浏览器分析')}</p></div>
 <div className="map-toolbar"><button className={threeD?'selected':''} onClick={()=>setThreeD(!threeD)}>{t(threeD?'3D 视角':'2D 平面')}</button>{workspace==='demo'&&catalog?.satellite&&<button className={settings.satellite?.visible?'selected':''} onClick={()=>toggle('satellite',!settings.satellite?.visible)}>{t('卫星底图')}</button>}<button disabled={!ready||exportBusy} onClick={exportPNG}>{t(exportBusy?'正在导出…':'导出 PNG')}</button><button aria-label={t('重置视角')} title={t('重置视角')} onClick={reset}><RotateCcw size={17}/></button></div>
 {layerCount>0&&<div className="stats-bar">{workspace==='demo'?<><div><span>{t('建筑数量')}</span><strong>{stats.count.toLocaleString()}</strong></div><div><span>{t('平均高度')}</span><strong>{stats.mean?.toFixed(1)??'—'}<small>{t('米')}</small></strong></div><div><span>{t('最高建筑')}</span><strong>{stats.max??'—'}<small>{t('米')}</small></strong></div></>:<><div><span>{t('图层数')}</span><strong>{layerCount}</strong></div><div><span>{t('要素数')}</span><strong>{featureCount.toLocaleString()}</strong></div></>}</div>}
 {workspace==='personal'&&!layerCount&&<div className="map-empty"><Upload size={36}/><h2>{t('在这里分析你的数据')}</h2><p>{t('GeoJSON、Shapefile 或 GeoTIFF')}</p><button className="primary" onClick={()=>setTab('upload')}>{t('导入本地数据')}</button></div>}
 {workspace==='demo'&&<div className="legend"><b>{t('建筑离地高度')}</b><span className="legend-unit">{t('米')}</span><div className="legend-ramp"/><div className="legend-ticks"><span>0</span><span>30</span><span>60</span><span>100</span><span>200+</span></div>{settings.population?.visible&&<div className="pop-legend"><b>{t('网格人数')}</b><div className="pop-ramp"/><div className="legend-ticks"><span>0</span><span>300</span><span>700</span><span>1,500</span><span>3,000+</span></div><p>2019-04-28 · 09:10</p></div>}</div>}
 {!ready&&<div className="loading">{t(error||'正在加载城市空间…')}</div>}
 {picked&&<div className="property-card"><div className="property-heading"><b>{t(metadata[picked.layer]?.name)} · {t('属性表')}</b><button aria-label={t('关闭要素属性')} onClick={()=>setPicked(null)}><X size={16}/></button></div><dl>{Object.entries(picked.feature.properties).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v==null?'NULL':String(v)}</dd></React.Fragment>)}</dl><button className="secondary" onClick={()=>{select({layer:picked.layer,ids:[featureId(picked.feature,metadata[picked.layer]?.idField||'stable_id')]});openTable(picked.layer);}}>{t('在属性表中选择')}</button></div>}
 {tableOpen&&dataset[tableLayer]&&<AttributeTable dataset={dataset} metadata={metadata} layer={tableLayer} onLayer={setTableLayer} selection={selection} onSelection={select} onClose={()=>setTableOpen(false)} settings={settings} onOpacity={opacity} onLocate={locate} onError={setError} height={tableHeight} onHeight={value=>setTableSize(clamp(value,110,Math.max(110,mapHeight-180)))}/>}
 <div className="rotation-hint">{t('右键拖动旋转 · 左键平移 · 滚轮缩放')}</div></section><aside><div className="aside-heading"><div><ChartNoAxesCombined size={21}/><h2>{t('分析工作台')}</h2></div><button className="connection-top" onClick={()=>{setTab('analysis');setAnalysisMode('chat');}}>{t('访客 · 本地功能')}</button></div><nav className="tabs">{tabs.map(([key,Icon,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);if(key==='attributes'&&dataset[tableLayer])setTableOpen(true);}}><Icon size={15}/>{t(label)}</button>)}</nav>
 <div className="aside-scroll">{error&&<div className="error" role="alert"><button aria-label={t('关闭提示')} onClick={()=>setError('')}><X size={14}/></button>{t(error)}</div>}{notice&&<div className="success-notice" role="status"><button aria-label={t('关闭提示')} onClick={()=>setNotice('')}><X size={14}/></button>{t(notice)}</div>}
 {tab==='analysis'&&<><div className="analysis-mode-select"><select aria-label={t('工作台模式')} value={analysisMode} onChange={e=>setAnalysisMode(e.target.value)}><option value="basic">{t('基础分析')}</option><option value="chat">{t("与GeoCIM对话")}</option></select></div>{analysisMode==='basic'?<AnalysisPanel key={workspace} dataset={dataset} metadata={metadata} layer={tableLayer} onLayer={setTableLayer} selection={selection} onResult={analysisResult} onError={setError} onTable={openTable} onUpload={()=>setTab('upload')} layerCount={layerCount}/>:<ChatPanel messages={messages} setMessages={setMessages} onCommand={handleChat} onBuilder={()=>setBuilderOpen(true)}/>}</>}
 {tab==='upload'&&<UploadPanel onImported={imported} onError={setError} layerCount={Object.values(metadata).filter(m=>m.workspace==='personal').length}/>}
 {tab==='layers'&&<><h3>{t('矢量图层')}</h3>{Object.keys(dataset).map(key=><div className="layer-row" key={key}><Toggle label={t(metadata[key]?.name||key)} checked={!!settings[key]?.visible} onChange={v=>toggle(key,v)}/><p>{dataset[key].features.length.toLocaleString()}{t(' 个要素')}</p><Transparency label={t((metadata[key]?.name||key)+'透明度')} value={settings[key]?.transparency??30} onChange={v=>opacity(key,v)}/>{metadata[key]?.density&&<div className="density-key"><b>{t('密度')} · {metadata[key].analysis.unit}</b><div className="density-ramp"/><span>0 — {metadata[key].density.max.toFixed(2)}</span></div>}
 {metadata[key]?.workspace==='personal'&&!metadata[key]?.analysis&&<label className="field-label">{t('三维高度字段（米，需自行确认）')}<select aria-label={t('三维高度字段（米，需自行确认）')+' '+metadata[key].name} value={metadata[key]?.heightField||''} onChange={e=>heightField(key,e.target.value)}><option value="">{t('不使用高度')}</option>{[...new Set(dataset[key].features.flatMap(f=>Object.keys(f.properties)))].map(f=><option key={f}>{f}</option>)}</select></label>}
 <div className="layer-actions"><button onClick={()=>openTable(key)}>{t('属性表')}</button><button onClick={()=>locate(dataset[key].features)}>{t('定位图层')}</button><button onClick={()=>downloadJSON(dataset[key],metadata[key].name+'.geojson')}>{t('下载 GeoJSON')}</button>{(metadata[key]?.workspace==='personal'||metadata[key]?.analysis)&&<button onClick={()=>removeLayer(key)}>{t('移除')}</button>}</div>{metadata[key]?.analysis&&<button className="secondary" onClick={()=>downloadJSON(metadata[key].analysis,metadata[key].name+'-parameters.json')}>{t('下载分析参数')}</button>}</div>)}
 {rasters.length>0&&<h3>{t('影像图层')}</h3>}{rasters.map(r=><div className="layer-row" key={r.id}><Toggle label={r.id==='satellite'?t('卫星底图（灰度）'):r.name} checked={!!settings[r.id]?.visible} onChange={v=>toggle(r.id,v)}/><Transparency label={t('图层透明度')} value={settings[r.id]?.transparency??0} onChange={v=>opacity(r.id,v)}/>{r.rasterInfo&&<><p>{r.rasterInfo.crs} · {r.rasterInfo.width} × {r.rasterInfo.height} · {r.rasterInfo.bands} {t('波段')}</p><p>{t('第 1 波段采样统计')} · n={r.rasterInfo.sampleCount}<br/>min={r.rasterInfo.min.toFixed(2)} · max={r.rasterInfo.max.toFixed(2)} · mean={r.rasterInfo.mean.toFixed(2)}</p><button className="secondary" onClick={()=>downloadJSON(r.rasterInfo,r.name+'-sample-stats.json')}>{t('下载统计结果')}</button></>}<div className="layer-actions"><button onClick={()=>setCamera({bounds:r.bounds||catalog.bounds,token:Date.now()})}>{t('定位图层')}</button>{r.workspace==='personal'&&<button onClick={()=>removeLayer(r.id)}>{t('移除')}</button>}</div></div>)}<h3>{t('浮动面板')}</h3><Transparency label={t('统计卡与图例透明度')} value={panelTransparency} onChange={setPanelTransparency}/></>}
 {tab==='attributes'&&<><h3>{t('图层属性表')}</h3>{Object.keys(dataset).map(key=><button className="secondary" key={key} onClick={()=>openTable(key)}>{t(metadata[key]?.name)} · {dataset[key].features.length.toLocaleString()}</button>)}<p className="help">{t('在下方属性表中按字段选择，也可以勾选单条记录。选中的要素以金色显示。')}</p>{dataset[tableLayer]&&<><Transparency label={t('当前图层透明度')} value={settings[tableLayer]?.transparency??30} onChange={v=>opacity(tableLayer,v)}/><Transparency label={t('当前选中要素透明度')} value={settings[tableLayer]?.selectedTransparency??15} disabled={selection.layer!==tableLayer||!selection.ids.length} onChange={v=>opacity(tableLayer,v,'selected')}/><button className="secondary" onClick={()=>setTab('analysis')}>{t('分析当前图层')}</button></>}</>}
 </div><div className="workspace-footer">{t('本地工具可用 · 模型连接待配置')}</div></aside></main>{builderOpen&&<Suspense fallback={<div className="circuit-overlay">{t("正在加载…")}</div>}><CircuitBuilder onDockHeight={setDockHeight} graph={graph} setGraph={setGraph} dataset={dataset} metadata={metadata} layerCount={layerCount} onResults={items=>{if(items.length){addItems(items,workspace);setNotice("电路运行完成，结果已加入地图。");setTableOpen(false);}}} onClose={()=>setBuilderOpen(false)}/></Suspense>}</div>;
}
createRoot(document.getElementById('root')).render(<LanguageProvider><App/></LanguageProvider>);
